defmodule Mibli.Repo.Migrations.AddFieldsToBook do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:books) do
      add :author, :text, null: true
      add :publication_year, :bigint, null: false
    end
  end

  def down do
    alter table(:books) do
      remove :publication_year
      remove :author
    end
  end
end
